export const CHARACTERS = [
  {
    id: 'warrior',
    name: '战士',
    icon: '⚔️',
    color: '#ff5f6d',
    weapon: 'shotgun',
    desc: '近战王者，霰弹枪高爆发',
    stats: { maxHp: 30, speed: 0.05, damage: 0.1 },
    ability: { name: '狂暴', desc: '3秒内攻速+80%', duration: 3, type: 'haste' },
  },
  {
    id: 'ranger',
    name: '射手',
    icon: '🏹',
    color: '#7dffb0',
    weapon: 'smg',
    desc: '远程穿透，高射速压制',
    stats: { maxHp: -10, speed: 0.1, attackSpeed: 0.15 },
    ability: { name: '穿透射击', desc: '5秒内子弹穿透+3', duration: 5, type: 'pierce' },
  },
  {
    id: 'mage',
    name: '法师',
    icon: '🔮',
    color: '#c46bff',
    weapon: 'tesla',
    desc: '连锁闪电，范围清场',
    stats: { maxHp: -15, speed: 0, area: 0.2, damage: 0.15 },
    ability: { name: '闪电风暴', desc: '4秒内连锁+4', duration: 4, type: 'chain' },
  },
  {
    id: 'assassin',
    name: '刺客',
    icon: '🗡️',
    color: '#ffe066',
    weapon: 'knife',
    desc: '高暴击，闪现突袭',
    stats: { maxHp: -5, speed: 0.15, critChance: 0.15, critDamage: 0.5 },
    ability: { name: '影袭', desc: '2秒内暴击率+40%', duration: 2, type: 'crit' },
  },
  {
    id: 'tank',
    name: '坦克',
    icon: '🛡️',
    color: '#41b8ff',
    weapon: 'orbital',
    desc: '超高血量，轨道护盾',
    stats: { maxHp: 60, speed: -0.05, armor: 0.15 },
    ability: { name: '钢铁壁垒', desc: '4秒内减伤60%', duration: 4, type: 'shield' },
  },
];

export const CHARACTER_MAP = Object.fromEntries(CHARACTERS.map((c) => [c.id, c]));
